### ISSUE TITLE
New two-row nav

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isfvideosite#1]
Editor | Docs
~~Downloads |~~ Showcase | Using ISF | Integrations | Developers

**Comment by jackturner** [comment]
@dlublin is this what we settled on? Was Editor going to link to the web-based editor or [be pluralized and link] to a disambiguation page w/ info on all the editors? And, if so, what the heck is on the Downloads page? (See #2)

**Comment by dlublin** [comment]
Let's nix downloads for the time being, otherwise I think this arrangement works well
Top row for external links, bottom row for local links.

**Comment by jackturner** [comment]
So Editor links to editor/shaders/code.isf.video?

This site still needs a clear pathway to the mac/win desktop editors. Right?

**Comment by dlublin** [comment]
1. Yes, editor would be a link to the online editor.
2. 
- The desktop editor is linked to on the integrations & using ISF pages.
- We can make one of the 'showcase' top blocks on the homepage about the desktop editor instead of having it as its own page.
- We should make it clear that the desktop editor is an available thing clearly on the editor site homepage. (maybe a strip that says 'also try the desktop editor for mac & win' that)
- This is sort of what I had in mind for the isf.vidvox.net homepage, which would prominently feature the ISF Editor

<img width="644" alt="screen shot 2019-02-19 at 12 10 38 pm" src="https://user-images.githubusercontent.com/461380/53290735-56984880-3776-11e9-9237-ae217124a0f8.png">

**Comment by jackturner** [comment]
oh, and it's gotta work on mobile. don't forget @jackturner !
